-- ==============================================================================
-- CATÁLOGO BASE DE EJERCICIOS (~200 Ejercicios)
-- Cubre Fuerza, Peso Corporal, Isométricos y Cardio.
-- ==============================================================================

INSERT INTO exercises (name, target_muscle, equipment, type) VALUES

  -- ==================== PECHO ====================
  ('Press de Banca Plano',          'Pecho',    'Barra',      'strength'),
  ('Press de Banca Inclinado',      'Pecho',    'Barra',      'strength'),
  ('Press de Banca Declinado',      'Pecho',    'Barra',      'strength'),
  ('Press Plano con Mancuernas',    'Pecho',    'Mancuernas', 'strength'),
  ('Press Inclinado con Mancuernas','Pecho',    'Mancuernas', 'strength'),
  ('Press Declinado con Mancuernas','Pecho',    'Mancuernas', 'strength'),
  ('Aperturas con Mancuernas',      'Pecho',    'Mancuernas', 'strength'),
  ('Aperturas Inclinadas',          'Pecho',    'Mancuernas', 'strength'),
  ('Cruces en Polea Alta',          'Pecho',    'Polea',      'strength'),
  ('Cruces en Polea Baja',          'Pecho',    'Polea',      'strength'),
  ('Pec Deck (Máquina de Aperturas)','Pecho',   'Máquina',    'strength'),
  ('Press de Pecho en Máquina',     'Pecho',    'Máquina',    'strength'),
  ('Pullover para Pecho',           'Pecho',    'Mancuernas', 'strength'),
  ('Flexiones (Push-ups)',          'Pecho',    'Ninguno',    'bodyweight'),
  ('Flexiones Diamante',            'Pecho',    'Ninguno',    'bodyweight'),
  ('Flexiones Declinadas',          'Pecho',    'Ninguno',    'bodyweight'),
  ('Flexiones Inclinadas',          'Pecho',    'Ninguno',    'bodyweight'),
  ('Flexiones con Palmada',         'Pecho',    'Ninguno',    'bodyweight'),
  ('Flexiones en Anillas',          'Pecho',    'Anillas',    'bodyweight'),
  ('Fondos en Paralelas (Dips)',    'Pecho',    'Ninguno',    'bodyweight'),
  ('Fondos Lastrados',              'Pecho',    'Equipamiento','strength'),
  ('Press Svend',                   'Pecho',    'Discos',     'strength'),
  ('Press en Máquina Smith',        'Pecho',    'Máquina',    'strength'),
  ('Cruces con Bandas Elásticas',   'Pecho',    'Bandas',     'strength'),

  -- ==================== ESPALDA ====================
  ('Peso Muerto Tradicional',       'Espalda',  'Barra',      'strength'),
  ('Peso Muerto Sumo',              'Espalda',  'Barra',      'strength'),
  ('Remo con Barra',                'Espalda',  'Barra',      'strength'),
  ('Remo con Barra Invertido',      'Espalda',  'Barra',      'strength'),
  ('Remo con Mancuerna (Serrucho)', 'Espalda',  'Mancuernas', 'strength'),
  ('Remo en Máquina T (T-Bar)',     'Espalda',  'Barra',      'strength'),
  ('Remo en Polea Baja',            'Espalda',  'Polea',      'strength'),
  ('Remo en Máquina Sentado',       'Espalda',  'Máquina',    'strength'),
  ('Remo Pendlay',                  'Espalda',  'Barra',      'strength'),
  ('Remo al Cuello (Face Pull)',    'Espalda',  'Polea',      'strength'),
  ('Jalón al Pecho',                'Espalda',  'Polea',      'strength'),
  ('Jalón al Pecho Agarre Estrecho','Espalda',  'Polea',      'strength'),
  ('Jalón al Pecho Agarre Inverso', 'Espalda',  'Polea',      'strength'),
  ('Jalón a un Brazo',              'Espalda',  'Polea',      'strength'),
  ('Pullover en Polea Alta',        'Espalda',  'Polea',      'strength'),
  ('Dominadas (Pull-ups)',          'Espalda',  'Ninguno',    'bodyweight'),
  ('Dominadas Supinas (Chin-ups)',  'Espalda',  'Ninguno',    'bodyweight'),
  ('Dominadas Neutras',             'Espalda',  'Ninguno',    'bodyweight'),
  ('Dominadas Lastradas',           'Espalda',  'Equipamiento','strength'),
  ('Dominadas Asistidas (Máquina)', 'Espalda',  'Máquina',    'strength'),
  ('Encogimientos con Barra',       'Espalda',  'Barra',      'strength'),
  ('Encogimientos con Mancuernas',  'Espalda',  'Mancuernas', 'strength'),
  ('Hiperextensiones',              'Espalda',  'Máquina',    'bodyweight'),
  ('Buenos Días (Good Mornings)',   'Espalda',  'Barra',      'strength'),
  ('Remo Invertido (Bodyweight)',   'Espalda',  'Ninguno',    'bodyweight'),

  -- ==================== PIERNAS ====================
  ('Sentadilla Libre (Back Squat)', 'Piernas',  'Barra',      'strength'),
  ('Sentadilla Frontal',            'Piernas',  'Barra',      'strength'),
  ('Sentadilla Goblet',             'Piernas',  'Kettlebell', 'strength'),
  ('Sentadilla Búlgara',            'Piernas',  'Mancuernas', 'strength'),
  ('Sentadilla en Máquina Smith',   'Piernas',  'Máquina',    'strength'),
  ('Sentadilla Hack',               'Piernas',  'Máquina',    'strength'),
  ('Sentadilla Sissy',              'Piernas',  'Ninguno',    'bodyweight'),
  ('Prensa de Piernas',             'Piernas',  'Máquina',    'strength'),
  ('Peso Muerto Rumano (RDL)',      'Piernas',  'Barra',      'strength'),
  ('Peso Muerto Piernas Rígidas',   'Piernas',  'Barra',      'strength'),
  ('Peso Muerto con Trap Bar',      'Piernas',  'Barra Hex',  'strength'),
  ('Zancadas (Lunges)',             'Piernas',  'Ninguno',    'bodyweight'),
  ('Zancadas con Mancuernas',       'Piernas',  'Mancuernas', 'strength'),
  ('Zancadas Inversas',             'Piernas',  'Mancuernas', 'strength'),
  ('Zancadas Caminando',            'Piernas',  'Mancuernas', 'strength'),
  ('Hip Thrust (Empuje de Cadera)', 'Piernas',  'Barra',      'strength'),
  ('Hip Thrust en Máquina',         'Piernas',  'Máquina',    'strength'),
  ('Puente de Glúteo',              'Piernas',  'Ninguno',    'bodyweight'),
  ('Extensión de Cuádriceps',       'Piernas',  'Máquina',    'strength'),
  ('Curl Femoral Tumbado',          'Piernas',  'Máquina',    'strength'),
  ('Curl Femoral Sentado',          'Piernas',  'Máquina',    'strength'),
  ('Curl Nórdico',                  'Piernas',  'Ninguno',    'bodyweight'),
  ('Máquina de Abductores',         'Piernas',  'Máquina',    'strength'),
  ('Máquina de Adductores',         'Piernas',  'Máquina',    'strength'),
  ('Elevación de Talones De Pie',   'Piernas',  'Máquina',    'strength'),
  ('Elevación de Talones Sentado',  'Piernas',  'Máquina',    'strength'),
  ('Elevación de Talones en Prensa','Piernas',  'Máquina',    'strength'),
  ('Step-ups (Subidas a Cajón)',    'Piernas',  'Mancuernas', 'strength'),
  ('Pistol Squat (A una pierna)',   'Piernas',  'Ninguno',    'bodyweight'),
  ('Kettlebell Swing',              'Piernas',  'Kettlebell', 'strength'),

  -- ==================== HOMBROS ====================
  ('Press Militar con Barra',       'Hombros',  'Barra',      'strength'),
  ('Press de Hombros Sentado',      'Hombros',  'Mancuernas', 'strength'),
  ('Press Arnold',                  'Hombros',  'Mancuernas', 'strength'),
  ('Press de Hombros en Máquina',   'Hombros',  'Máquina',    'strength'),
  ('Press en Máquina Smith Sentado','Hombros',  'Máquina',    'strength'),
  ('Elevaciones Laterales',         'Hombros',  'Mancuernas', 'strength'),
  ('Elevaciones Laterales en Polea','Hombros',  'Polea',      'strength'),
  ('Elevaciones Frontales con Disco','Hombros', 'Discos',     'strength'),
  ('Elevaciones Frontales Mancuerna','Hombros', 'Mancuernas', 'strength'),
  ('Elevaciones Frontales en Polea','Hombros',  'Polea',      'strength'),
  ('Pájaros (Deltoides Posterior)', 'Hombros',  'Mancuernas', 'strength'),
  ('Pájaros en Máquina (Pec Deck)', 'Hombros',  'Máquina',    'strength'),
  ('Pájaros en Polea Alta',         'Hombros',  'Polea',      'strength'),
  ('Remo al Mentón con Barra',      'Hombros',  'Barra',      'strength'),
  ('Remo al Mentón en Polea',       'Hombros',  'Polea',      'strength'),
  ('Face Pull en Polea',            'Hombros',  'Polea',      'strength'),
  ('Pino contra la Pared (Hold)',   'Hombros',  'Ninguno',    'isometric'),
  ('Flexiones de Pino (HSPU)',      'Hombros',  'Ninguno',    'bodyweight'),

  -- ==================== BÍCEPS ====================
  ('Curl de Bíceps con Barra',      'Brazos',   'Barra',      'strength'),
  ('Curl de Bíceps con Barra Z',    'Brazos',   'Barra Z',    'strength'),
  ('Curl de Bíceps con Mancuernas', 'Brazos',   'Mancuernas', 'strength'),
  ('Curl Martillo',                 'Brazos',   'Mancuernas', 'strength'),
  ('Curl Martillo Cruzado',         'Brazos',   'Mancuernas', 'strength'),
  ('Curl en Banco Scott',           'Brazos',   'Máquina',    'strength'),
  ('Curl Predicador con Barra Z',   'Brazos',   'Barra Z',    'strength'),
  ('Curl Concentrado',              'Brazos',   'Mancuernas', 'strength'),
  ('Curl Araña (Spider Curl)',      'Brazos',   'Mancuernas', 'strength'),
  ('Curl en Polea Baja',            'Brazos',   'Polea',      'strength'),
  ('Curl en Polea Alta (Doble)',    'Brazos',   'Polea',      'strength'),
  ('Curl Inverso con Barra',        'Brazos',   'Barra',      'strength'),
  ('Curl 21s',                      'Brazos',   'Barra',      'strength'),

  -- ==================== TRÍCEPS ====================
  ('Extensión de Tríceps en Polea', 'Brazos',   'Polea',      'strength'),
  ('Extensión con Cuerda en Polea', 'Brazos',   'Polea',      'strength'),
  ('Press Francés (Rompecráneos)',  'Brazos',   'Barra Z',    'strength'),
  ('Press Francés con Mancuernas',  'Brazos',   'Mancuernas', 'strength'),
  ('Press de Banca Agarre Estrecho','Brazos',   'Barra',      'strength'),
  ('Extensión Tras Nuca Mancuerna', 'Brazos',   'Mancuernas', 'strength'),
  ('Extensión Tras Nuca en Polea',  'Brazos',   'Polea',      'strength'),
  ('Patada de Tríceps',             'Brazos',   'Mancuernas', 'strength'),
  ('Patada de Tríceps en Polea',    'Brazos',   'Polea',      'strength'),
  ('Fondos entre Bancos',           'Brazos',   'Ninguno',    'bodyweight'),
  ('Máquina de Fondos para Tríceps','Brazos',   'Máquina',    'strength'),

  -- ==================== ANTEBRAZOS ====================
  ('Curl de Muñeca Supino',         'Brazos',   'Barra',      'strength'),
  ('Curl de Muñeca Prono',          'Brazos',   'Barra',      'strength'),
  ('Paseo del Granjero',            'Brazos',   'Mancuernas', 'strength'),
  ('Colgado en Barra (Dead Hang)',  'Brazos',   'Ninguno',    'isometric'),

  -- ==================== CORE / ABDOMINALES ====================
  ('Crunch Abdominal',              'Core',     'Ninguno',    'bodyweight'),
  ('Crunch Abdominal en Polea',     'Core',     'Polea',      'strength'),
  ('Crunch en Máquina',             'Core',     'Máquina',    'strength'),
  ('Crunch Declinado',              'Core',     'Ninguno',    'bodyweight'),
  ('Elevación de Piernas Colgado',  'Core',     'Ninguno',    'bodyweight'),
  ('Elevación de Rodillas Colgado', 'Core',     'Ninguno',    'bodyweight'),
  ('Elevación de Piernas Tumbado',  'Core',     'Ninguno',    'bodyweight'),
  ('Rueda Abdominal (Ab Roller)',   'Core',     'Equipamiento','strength'),
  ('Plancha Abdominal (Plank)',     'Core',     'Ninguno',    'isometric'),
  ('Plancha Lateral',               'Core',     'Ninguno',    'isometric'),
  ('Plancha con Peso',              'Core',     'Discos',     'isometric'),
  ('Hollow Hold',                   'Core',     'Ninguno',    'isometric'),
  ('L-Sit',                         'Core',     'Ninguno',    'isometric'),
  ('Twist Ruso (Russian Twist)',    'Core',     'Disco',      'strength'),
  ('Leñador en Polea (Woodchopper)','Core',     'Polea',      'strength'),
  ('Bicicleta Abdominal',           'Core',     'Ninguno',    'bodyweight'),
  ('Toes to Bar (Pies a la barra)', 'Core',     'Ninguno',    'bodyweight'),
  ('V-Ups (Abdominales en V)',      'Core',     'Ninguno',    'bodyweight'),
  ('Abdominales Mariposa',          'Core',     'Ninguno',    'bodyweight'),
  ('Superman Hold',                 'Core',     'Ninguno',    'isometric'),

  -- ==================== CARDIO Y ACONDICIONAMIENTO ====================
  ('Cinta de Correr',               'Cardio',   'Máquina',    'cardio'),
  ('Cinta de Correr (Inclinación)', 'Cardio',   'Máquina',    'cardio'),
  ('Bicicleta Estática',            'Cardio',   'Máquina',    'cardio'),
  ('Bicicleta de Spinning',         'Cardio',   'Máquina',    'cardio'),
  ('Bicicleta Airbike (Assault)',   'Cardio',   'Máquina',    'cardio'),
  ('Remo Ergómetro',                'Cardio',   'Máquina',    'cardio'),
  ('Elíptica',                      'Cardio',   'Máquina',    'cardio'),
  ('Escaladora (Stairmaster)',      'Cardio',   'Máquina',    'cardio'),
  ('Salto a la Comba',              'Cardio',   'Equipamiento','cardio'),
  ('Carrera Continua (Exterior)',   'Cardio',   'Ninguno',    'cardio'),
  ('Sprints',                       'Cardio',   'Ninguno',    'cardio'),
  ('Natación',                      'Cardio',   'Ninguno',    'cardio'),
  ('Ciclismo (Exterior)',           'Cardio',   'Ninguno',    'cardio'),
  ('Saco de Boxeo',                 'Cardio',   'Equipamiento','cardio'),
  ('Battle Ropes (Cuerdas)',        'Cardio',   'Equipamiento','cardio'),
  ('Trineo (Sled Push)',            'Cardio',   'Equipamiento','strength'),
  ('Trineo (Sled Pull)',            'Cardio',   'Equipamiento','strength'),

  -- ==================== FULL BODY / HIIT / OTROS ====================
  ('Burpees',                       'Full Body','Ninguno',    'bodyweight'),
  ('Mountain Climbers',             'Full Body','Ninguno',    'bodyweight'),
  ('Jumping Jacks',                 'Full Body','Ninguno',    'bodyweight'),
  ('Muscle-Up en Barra',            'Full Body','Ninguno',    'bodyweight'),
  ('Muscle-Up en Anillas',          'Full Body','Anillas',    'bodyweight'),
  ('Clean and Jerk (Dos tiempos)',  'Full Body','Barra',      'strength'),
  ('Snatch (Arrancada)',            'Full Body','Barra',      'strength'),
  ('Thruster con Barra',            'Full Body','Barra',      'strength'),
  ('Thruster con Mancuernas',       'Full Body','Mancuernas', 'strength'),
  ('Turkish Get-Up',                'Full Body','Kettlebell', 'strength')

ON CONFLICT (name) DO NOTHING;